version: '3.9'
services:
  mongodb:
    container_name: mongodb
    build: ./database
    ports:
      - "21001:27017"
  apinotepatient:
    container_name: apinotepatient
    build: .
    ports:
      - "21000:8082"
    depends_on:
      - mongodb
    environment:
      spring.data.mongodb.uri: "mongodb://mongodb:27017/Notes"





